# Analyzer configuration
# project_root 可以是绝对路径或相对于本配置文件所在目录的相对路径
# project_root: benchmarks/c-algorithm
# project_root: benchmarks/crown/Input

project_root: benchmarks/test
# project_root: benchmarks/translate_littlefs_fuse

# 输出目录配置，可以是绝对路径或相对于本配置文件所在目录的相对路径
output_root: analyzer/output
rust_output: output